# Generated by Django 4.1.4 on 2023-03-20 19:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_uploaded_avatar",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="default.png", upload_to=users.models.avatar_image_file_path
            ),
        ),
    ]
