# Generated by Django 4.1.4 on 2023-04-28 19:59

from django.db import migrations, transaction
from django.core.management import call_command


def forwards_func(apps, schema_editor):
    with transaction.atomic():
        call_command("loaddata", "users_fixture_data.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_profile_avatar"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
