# Generated by Django 4.1.4 on 2023-04-28 18:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_auto_20230428_2011"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="media/default.png",
                upload_to=users.models.avatar_image_file_path,
            ),
        ),
    ]
