# Generated by Django 4.1.4 on 2022-12-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_task_assignees_task_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_types', to='app.tasktype'),
        ),
    ]
