# Generated by Django 4.1.4 on 2023-02-18 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('app', '0004_remove_task_assignees_task_assignees'), ('app', '0005_remove_task_task_type_task_task_type'), ('app', '0006_task_created_date'), ('app', '0007_remove_task_task_type_task_task_type'), ('app', '0008_alter_task_deadline'), ('app', '0009_alter_task_options_profile'), ('app', '0010_remove_profile_bio'), ('app', '0011_alter_position_name'), ('app', '0012_rename_address_profile_main_programming_language'), ('app', '0013_delete_profile'), ('app', '0014_alter_task_options'), ('app', '0015_alter_worker_position'), ('app', '0016_alter_worker_position'), ('app', '0017_alter_task_task_type_alter_worker_position'), ('app', '0018_remove_task_assignees_task_assignee'), ('app', '0019_alter_worker_position')]

    dependencies = [
        ('app', '0003_rename_title_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_types', to='app.tasktype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_date'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Project manager', 'Project Manager'), ('Designer', 'Designer'), ('Devops', 'DevOps'), ('QA', 'QA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='app.position'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='app.position'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='app.tasktype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='app.position'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='app.position'),
        ),
    ]
