# Generated by Django 4.1.4 on 2022-12-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Project manager', 'Project Manager'), ('Designer', 'Designer'), ('Devops', 'DevOps'), ('QA', 'QA')], max_length=255),
        ),
    ]
