# Generated by Django 4.1.4 on 2022-12-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_position_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='main_programming_language',
        ),
    ]
