# Generated by Django 4.1.4 on 2022-12-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_address_profile_main_programming_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
