# Generated by Django 4.1.4 on 2023-01-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_date'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
